import { CourseProps } from "./interface";
import Frontend from "@/assets/images/frontend.jpg";
import Backend from "@/assets/images/backend.png";
import Intro from "@/assets/images/intro.jpg";

export const courses: CourseProps[] = [
  {
    id: 1,
    image: Frontend,
    title: "Samson",
    course: "Frontend Development",
    price: "₦50,000",
    duration: "8 Weeks",
    level: "Beginner",
    rating: 4,
    description: "Learn HTML, CSS, JS, and React.",
    progress: 65,
  },
  {
    id: 2,
    image: Backend,
    title: "Samson",
    course: "Backend Development",
    price: "₦50,000",
    duration: "8 Weeks",
    level: "Beginner",
    rating: 4,
    description: "Master server-side development.",
    progress: 100,
  },
  {
    id: 3,
    image: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?auto=format&fit=crop&w=800&h=400",
    title: "Gbenga",
    course: "Mobile Development",
    price: "₦50,000",
    duration: "6 Weeks",
    level: "Intermediate",
    rating: 5,
    description: "Build cross-platform apps.",
    progress: 30,
  },
  {
    id: 4,
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=800&h=400",
    title: "Feranmi",
    course: "Data Science",
    price: "₦50,000",
    duration: "10 Weeks",
    level: "Advanced",
    rating: 4,
    description: "Learn Python, Pandas & ML.",
    progress: 100,
  },
  {
    id: 5,
    image: Intro,
    title: "Samson",
    course: "Intro to Computer",
    price: "₦50,000",
    duration: "8 Weeks",
    level: "Beginner",
    rating: 4,
    description: "Fundamentals of computer science.",
    progress: 0,
  },
];
